coffeshop/coffeapp/urls.py
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'coffeapp'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),
    path('', views.home, name= 'home'),
    path('new-product/', views.createProduct, name='new-product'),
    path('products-page/', views.productsPage, name='products-page'),
    path('manage-product/',views.manageProduct, name='manage-product'),
    path('cart/', views.view_cart, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout, name='checkout'),]


urlpatterns+= static(settings.MEDIA_URL, documnet_root= settings.MEDIA_ROOT)

coffeshop/coffeshop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coffeapp.urls')),
]

coffeshop/coffeapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError


def validate_phone_number(value):
    if len(str(value)) == 10:
        raise ValidationError('Phone number must be exactly 10 digits')

class User(AbstractUser):
    username = models.CharField(max_length=255, unique=True, primary_key=True, db_index=True)
    email = models.EmailField(max_length=255, unique=True, db_index=True)
    phone_number = models.IntegerField(
        unique=True, null= True,
        validators=[validate_phone_number],db_index=True)
    USERNAME_FIELD= 'username'
    REQUIRED_FIELDS= []





class Users(models.Model):
    username = models.CharField(max_length=255, unique=True, primary_key=True, db_index=True)
    full_name = models.CharField(max_length=255, db_index=True)
    email = models.EmailField(max_length=255, unique=True, db_index=True)
    password = models.CharField(max_length=255, unique=True, db_index=False)
    phone_number = models.BigIntegerField(
        unique=True,
        validators=[
            MinValueValidator(10000000000),
            MaxValueValidator(99999999999),
            validate_phone_number],db_index=True)
    

    class Meta:
        ordering = ('-username',)

class Orders(models.Model):
    order_id = models.IntegerField(db_index=True, validators=[MinValueValidator(1), MaxValueValidator(10)], unique=True, primary_key=True)
    username = models.CharField(max_length=255, db_index=True)
    products = models.CharField(max_length=255)
    purchase_amount = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    type = models.BinaryField(max_length=1, db_index=True)

    class Meta:
        ordering = ('-order_id',)

class Users_Orders(models.Model):
    users_username = models.ForeignKey(User, on_delete=models.CASCADE, to_field='username', related_name='orders', db_column='username')
    orders_order_id = models.ForeignKey(Orders, on_delete=models.CASCADE, to_field='order_id', db_column='order_id')

    class Meta:
        ordering = ('-users_username',)

class Products(models.Model):
    PRODUCT_TYPES = [
        ('CD', 'Cold Drinks'),
        ('CA', 'Cakes'),
        ('MS', 'Milkshakes'),
        ('HD', 'Hot Drinks'),
    ]


    avatar = models.ImageField(null= True, default="coffee_shop_logo_whithout_background_1.png")
    id = models.IntegerField(primary_key=True, db_index=True, db_column='id',  unique=True)
    name = models.CharField(max_length=255, db_index=True, unique=True)
    sugar = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=0)
    coffee = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)],default=0)
    flour = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)],default=0)
    chocolate = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)],default=0)
    vertical = models.CharField(max_length=2, choices=PRODUCT_TYPES, db_index=True)
    price = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True )

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return self.name

class Orders_Products(models.Model):
    id = models.IntegerField(primary_key=True, db_index=True, db_column='id', validators=[MinValueValidator(1), MaxValueValidator(10)], unique=True)
    orders_order_id = models.ForeignKey(Orders, on_delete=models.CASCADE, to_field='order_id', db_column='order_id')
    products_id = models.ForeignKey(Products, on_delete=models.CASCADE, to_field='id', db_column='products_id')

    class Meta:
        ordering = ('-id',)

class Admins(models.Model):
    username = models.CharField(max_length=255, unique=True, primary_key=True)
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ('-username',)

class Storage(models.Model):
    NAME_CHOICES= [('sugar','sugar'), ('coffee','coffee'), ('flour','flour'), ('chocolate','chocolate')]
    name = models.CharField(choices=NAME_CHOICES, max_length=255, unique=True, primary_key=True)
    amount = models.IntegerField(default=0)
    coffee = models.IntegerField(default=0)
    sugar = models.IntegerField(default=0)
    chocolate = models.IntegerField(default=0)
    flour = models.IntegerField(default=0)

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

coffeshop/coffeapp/forms.py
from django import forms
from .models import Users, Orders, Products, Admins, Storage, User

# این فرم مربوط به جدول Users در فایل models.py است
class MyUserCreationForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['username', 'full_name', 'email', 'password', 'phone_number']

class LoginForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput)


    
# این فرم مربوط به جدول Orders در فایل models.py است
class OrdersForm(forms.ModelForm):
    class Meta:
        model = Orders
        exclude = ('type',)  

# این فرم مربوط به جدول Products در فایل models.py است
class ProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        exclude= ['id']

# این فرم مربوط به جدول Admins در فایل models.py است
class AdminsForm(forms.ModelForm):
    class Meta:
        model = Admins
        fields = ['username', 'email', 'password']

# این فرم مربوط به جدول Storage در فایل models.py است
class StorageForm(forms.ModelForm):
    class Meta:
        model = Storage
        fields = ['coffee', 'sugar', 'chocolate', 'flour']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.initial = ''


class AddToCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=10)

coffeshop/coffeapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotAllowed
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.db.models.functions import TruncDate
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from .forms import *
from .models import *



# def signin(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user = authenticate(request, username=username, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect('home')  
#             else:
#                 return render(request, 'sign_in_page.html', {'form': form})
#     elif request.method == 'GET':
#         form = LoginForm()
#         return render(request, 'sign_in_page.html', {'form': form})

def signin(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('coffeapp:home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username= username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('coffeapp:home')
        else:
            messages.error(request, 'Username OR password does not exit')

    context = {'page': page}
    return render(request, 'sign_in_page.html', context)


def logoutUser(request):
    logout(request)
    return redirect('coffeapp:home')


def registerPage(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('coffeapp:home')
        else:
            messages.error(request, 'An error occurred during registration')

    return render(request, 'sign_up_page.html', {'form': form})

# def newproductPage(request):
#     form = ProductsForm(request.POST)
#     if form.is_valid():


def home(request):
    products= Products.objects.all
    context= {'products': products}
    return render(request, 'home.html', context)

@login_required(login_url='coffeapp:signin')
def productsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    products= Products.objects.filter(Q(vertical__icontains= q))
    product_types = Products.vertical
    product_prices= Products.price
    context= {'products': products, 'product_types': product_types, 'product_prices':product_prices}
    return render(request, 'products.html', context)

def createProduct(request):
    if request.user != User.is_superuser:
        return HttpResponse('You are not allowed here!!!!')

    form = ProductsForm()
    if request.method == 'POST':
        form= ProductsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('coffeapp:home')

    context={'form': form}
    return render(request, 'new_product.html', context)


def manageProduct(request):
    form =StorageForm(request.POST)
    storage = Storage.objects.first()  # assuming only one Storage object
    if request.method == 'POST':
        form = StorageForm(request.POST, instance=storage)
        if form.is_valid():
            form.save()
        return redirect('coffeapp:manage-product')
    else:
        form = StorageForm(instance=storage)



    context={'form': form}
    return render(request, 'manage-product.html', context)

@login_required
def view_cart(request):
    try:
        cart = Cart.objects.get(user=request.user)
    except Cart.DoesNotExist:
        cart = None
    
    if request.method == 'GET':
        if cart:
            items = CartItem.objects.filter(cart=cart)
            total = sum(item.product.price * item.quantity for item in items)
            return render(request, 'cart.html', {'items': items, 'total': total})
        else:
            return render(request, 'cart.html', {'items': [], 'total': 0})
    else:
        return HttpResponseNotAllowed(['GET'], 'Only GET method is allowed.')

@login_required
def add_to_cart(request, product_id):
    try:
        product = Products.objects.get(id=product_id)
    except Products.DoesNotExist:
        product = None
    quantity = 1

    # بررسی موجودی انبار
    ingredients = {
        'sugar': product.sugar * quantity,
        'coffee': product.coffee * quantity,
        'flour': product.flour * quantity,
        'chocolate': product.chocolate * quantity
    }
    storage = Storage.objects.first()
        
    if storage.coffee < product.coffee:
        messages.error(request, f'موجودی قهوه کافی نیست.')
        return HttpResponse('Not allowed')
    elif storage.sugar < product.sugar:
        messages.error(request, f'موجودی شکر کافی نیست.')
        return HttpResponse('Not allowed')
    elif storage.chocolate < product.chocolate:
        messages.error(request, f'موجودی شکلات کافی نیست.')
        return HttpResponse('Not allowed')
    elif storage.flour < product.flour:
        messages.error(request, f'موجودی آرد کافی نیست.')
        return HttpResponse('Not allowed')
    
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    
    if not created:
        cart_item.quantity += quantity
        cart_item.save()
    else:
        cart_item.quantity = quantity
        cart_item.save()
    
    messages.success(request, 'محصول به سبد خرید اضافه شد.')
    return redirect('coffeapp:cart')




@login_required
def checkout(request):
    if request.method == 'POST':
        order_type = request.POST.get('order_type')
        cart = Cart.objects.get(user=request.user)
        items = CartItem.objects.filter(cart=cart)
        
        # ایجاد سفارش
        order = Orders.objects.create(
            username=request.user.username,
            products=', '.join([item.product.name for item in items]),
            purchase_amount=sum(item.product.price * item.quantity for item in items),
            type=order_type
        )
        
        # کم کردن از موجودی انبار
        for item in items:
            product = item.product
            Storage.objects.filter(name='sugar').update(amount=f'{'amount'}' - product.sugar * item.quantity)
            Storage.objects.filter(name='coffee').update(amount=f'{'amount'}' - product.coffee * item.quantity)
            Storage.objects.filter(name='flour').update(amount=f'{'amount'}' - product.flour * item.quantity)
            Storage.objects.filter(name='chocolate').update(amount=f'{'amount'}' - product.chocolate * item.quantity)
        
        # پاک کردن سبد خرید
        cart.delete()
        
        messages.success(request, 'سفارش شما با موفقیت ثبت شد.')
        return redirect('order_confirmation')
    
    return redirect('view_cart')



@login_required
def order_history(request):
    if request.method == 'GET':
        orders = Orders.objects.filter(username=request.user.username).order_by('-order_id')
        return render(request, 'order_history.html', {'orders': orders})
    else:
        return redirect('coffeapp:order_history')



@login_required(login_url='coffeapp:signin')
def store_management(request):
    if request.method == 'GET':
        # نمودار فروش
        sales_data = Orders.objects.annotate(date=TruncDate('created_at')).values('date').annotate(total_sales=Sum('purchase_amount')).order_by('date')
        
        # اطلاعات انبار
        storage_data = Storage.objects.all()
        
        # لیست محصولات
        products = Products.objects.all()
        
        context = {
            'sales_data': sales_data,
            'storage_data': storage_data,
            'products': products,
        }
        return render(request, 'store_management.html', context)
    else:
        return redirect('coffeapp:store_management')

coffeshop/coffeapp/templates/cart.html
{% extends 'main.html' %}

{% block content %}
<h1>سبد خرید</h1>
{% if items %}
    <ul>
    {% for item in items %}
        <li>{{ item.product.name }} - تعداد: {{ item.quantity }} - قیمت: {{ item.product.price }}</li>
    {% endfor %}
    </ul>
    <p>مجموع: {{ total }}</p>
    <form method="post" action="{% url 'checkout' %}">
        {% csrf_token %}
        <label>نوع سفارش:</label>
        <select name="order_type">
            <option value="takeaway">بیرون بر</option>
            <option value="dine_in">حضوری</option>
        </select>
        <button type="submit">پرداخت</button>
    </form>
{% else %}
    <p>سبد خرید شما خالی است.</p>
{% endif %}
{% endblock %}

coffeshop/coffeapp/templates/home-new.html
{% extends 'main.html' %}

{% block content %}
<div class="ecommerce-site">
  <img class="sign-out-squre-light" src="../assets/vectors/sign_out_squre_light_4_x2.svg" />
  <img class="trolly" src="../assets/vectors/trolly_3_x2.svg" />
  <img class="wallet" src="../assets/vectors/wallet_2_x2.svg" />
  <div class="coffee-shop-logo-whithout-background-1">
  </div>
  <div class="menu-3">
    <div class="vector-7">
    </div>
    <div class="vector-8">
    </div>
    <div class="vector-9">
    </div>
  </div>
  <div class="navigation">
    <div class="items">
      <img class="sign-out-squre-light" src="../assets/vectors/sign_out_squre_light_4_x2.svg" />
      <img class="trolly" src="../assets/vectors/trolly_3_x2.svg" />
      <img class="wallet" src="../assets/vectors/wallet_2_x2.svg" />
    </div>
    <div class="coffee-shop-logo-whithout-background-1">
    </div>
    <div class="button-1">
      <div class="menu-3">
        <div class="vector-7">
        </div>
        <div class="vector-8">
        </div>
        <div class="vector-9">
        </div>
      </div>
    </div>
  </div>
  <div class="container-10">
  کافه کلاسیک
  </div>
  <span class="container-12">
  جهت دیدن محصولات&gt;
  </span>
  <div class="button">
    <span class="container-12">
    جهت دیدن محصولات&gt;
    </span>
  </div>
  <div class="header-with-image">
    <div class="container-10">
    کافه کلاسیک
    </div>
    <div class="copy-7">
      <div class="button">
        <span class="container-12">
        جهت دیدن محصولات&gt;
        </span>
      </div>
    </div>
  </div>
  <div class="container-9">
  محصولات پیشنهادی
  </div>
  <div>
    <div class="image-3">
    </div>
    <div class="product-2">
    Product 
    </div>
    <div class="description-of-first-product">
    Description of first product
    </div>
    <span class="container-5">
    $10.99
    </span>
    <div class="image-4">
    </div>
    <div class="product-3">
    Product
    </div>
    <div class="description-of-second-product">
    Description of second product
    </div>
    <span class="container-6">
    $10.99
    </span>
    <div class="image-5">
    </div>
    <div class="product-4">
    Product
    </div>
    <div class="description-of-third-product">
    Description of third product
    </div>
    <span class="container-7">
    $10.99
    </span>
    <div class="image-6">
    </div>
    <div class="product-5">
    Product
    </div>
    <div class="description-of-fourth-product">
    Description of fourth product
    </div>
    <span class="container-8">
    $10.99
    </span>
  </div>
  <div class="container-4">
  پرفروش ها
  </div>
  <div>
    <div class="image-1">
    </div>
    <div class="product-1">
    Product
    </div>
    <div class="description-of-lower-product">
    Description of lower product
    </div>
    <span class="container-1">
    $10.99
    </span>
    <div class="image">
    </div>
    <div class="product">
    Product 
    </div>
    <div class="description-of-top-product">
    Description of top product
    </div>
    <span class="container">
    $10.99
    </span>
    <div class="image-7">
    </div>
    <div class="product-6">
    Product
    </div>
    <div class="description-of-lower-product-1">
    Description of lower product
    </div>
    <span class="container-13">
    $10.99
    </span>
    <div class="image-2">
    </div>
  </div>
  <div>
    <div class="container-2">
    درباره ما
    </div>
    <span class="container-3">
    کافه کلاسیک در سال 1403 در جهت تامین کافه با کیفیت برای دانشجویان در خیابان آزادی تاسیس شد
    </span>
  </div>
  
  <div class="coffee-shop-logo-whithout-background-2">
  </div>
  <img class="union" src="../assets/vectors/union_x2.svg" />
  <img class="union-1" src="../assets/vectors/union_2_x2.svg" />
  <img class="icon" src="../assets/vectors/icon_13_x2.svg" />
  <img class="icon-1" src="../assets/vectors/icon_16_x2.svg" />
  <img class="icon-2" src="../assets/vectors/icon_5_x2.svg" />
  <img class="icon-3" src="../assets/vectors/icon_10_x2.svg" />
  <div class="navigation-footer">
    <div class="divider">
    </div>
    <div class="container">
      <div class="coffee-shop-logo-whithout-background-2">
      </div>
      <div class="items-1">
        <img class="union" src="../assets/vectors/union_x2.svg" />
        <img class="union-1" src="../assets/vectors/union_2_x2.svg" />
      </div>
    </div>
    <div class="social-icons">
      <div class="buttons-icon">
        <img class="icon" src="../assets/vectors/icon_13_x2.svg" />
      </div>
      <div class="buttons-icon-1">
        <img class="icon-1" src="../assets/vectors/icon_16_x2.svg" />
      </div>
      <div class="buttons-icon-2">
        <img class="icon-2" src="../assets/vectors/icon_5_x2.svg" />
      </div>
      <div class="buttons-icon-3">
        <img class="icon-3" src="../assets/vectors/icon_10_x2.svg" />
      </div>
    </div>
  </div>
  <div class="shop">
    <div class="navigation">
      <div class="items">
        <img class="sign-out-squre-light" src="../assets/vectors/sign_out_squre_light_4_x2.svg" />
        <img class="trolly" src="../assets/vectors/trolly_3_x2.svg" />
        <img class="wallet" src="../assets/vectors/wallet_2_x2.svg" />
      </div>
      <div class="coffee-shop-logo-whithout-background-1">
      </div>
      <div class="button-1">
        <div class="menu-3">
          <div class="vector-7">
          </div>
          <div class="vector-8">
          </div>
          <div class="vector-9">
          </div>
        </div>
      </div>
    </div>
    <div class="header-with-image">
      <div class="container-10">
      کافه کلاسیک
      </div>
      <div class="copy-7">
        <div class="button">
          <span class="container-12">
          جهت دیدن محصولات&gt;
          </span>
        </div>
      </div>
    </div>
    <div class="container-9">
    محصولات پیشنهادی
    </div>
    <div class="card-grid">
      <div class="card-2">
        <div class="image-3">
        </div>
        <div class="copy-3">
          <div class="product-2">
          Product 
          </div>
          <div class="description-of-first-product">
          Description of first product
          </div>
          <span class="container-5">
          $10.99
          </span>
        </div>
      </div>
      <div class="card-3">
        <div class="image-4">
        </div>
        <div class="copy-4">
          <div class="product-3">
          Product
          </div>
          <div class="description-of-second-product">
          Description of second product
          </div>
          <span class="container-6">
          $10.99
          </span>
        </div>
      </div>
      <div class="card-4">
        <div class="image-5">
        </div>
        <div class="copy-5">
          <div class="product-4">
          Product
          </div>
          <div class="description-of-third-product">
          Description of third product
          </div>
          <span class="container-7">
          $10.99
          </span>
        </div>
      </div>
      <div class="card-5">
        <div class="image-6">
        </div>
        <div class="copy-6">
          <div class="product-5">
          Product
          </div>
          <div class="description-of-fourth-product">
          Description of fourth product
          </div>
          <span class="container-8">
          $10.99
          </span>
        </div>
      </div>
    </div>
    <div class="container-4">
    پرفروش ها
    </div>
    <div class="card-list">
      <div class="card-1">
        <div class="image-1">
        </div>
        <div class="copy-1">
          <div class="product-1">
          Product
          </div>
          <div class="description-of-lower-product">
          Description of lower product
          </div>
          <span class="container-1">
          $10.99
          </span>
        </div>
      </div>
      <div class="card">
        <div class="image">
        </div>
        <div class="copy">
          <div class="product">
          Product 
          </div>
          <div class="description-of-top-product">
          Description of top product
          </div>
          <span class="container">
          $10.99
          </span>
        </div>
      </div>
      <div class="card-6">
        <div class="image-7">
        </div>
        <div class="copy-8">
          <div class="product-6">
          Product
          </div>
          <div class="description-of-lower-product-1">
          Description of lower product
          </div>
          <span class="container-13">
          $10.99
          </span>
        </div>
      </div>
    </div>
    <div class="card-big">
      <div class="image-2">
      </div>
      <div class="copy-2">
        <div class="container-2">
        درباره ما
        </div>
        <span class="container-3">
        کافه کلاسیک در سال 1403 در جهت تامین کافه با کیفیت برای دانشجویان در خیابان آزادی تاسیس شد
        </span>
      </div>
    </div>
    <div class="navigation-footer">
      <div class="divider">
      </div>
      <div class="container">
        <div class="coffee-shop-logo-whithout-background-2">
        </div>
        <div class="items-1">
          <img class="union" src="../assets/vectors/union_x2.svg" />
          <img class="union-1" src="../assets/vectors/union_2_x2.svg" />
        </div>
      </div>
      <div class="social-icons">
        <div class="buttons-icon">
          <img class="icon" src="../assets/vectors/icon_13_x2.svg" />
        </div>
        <div class="buttons-icon-1">
          <img class="icon-1" src="../assets/vectors/icon_16_x2.svg" />
        </div>
        <div class="buttons-icon-2">
          <img class="icon-2" src="../assets/vectors/icon_5_x2.svg" />
        </div>
        <div class="buttons-icon-3">
          <img class="icon-3" src="../assets/vectors/icon_10_x2.svg" />
        </div>
      </div>
    </div>
  </div>
  <span class="container-11">
  لذت قهوه خوب با کافه کلاسیک
  </span>
</div>
{% endblock content %}

coffeshop/coffeapp/templates/home.html
{% extends 'main.html' %}

{% block content %}

<div>
  {% for product in products %}
  <a href="{% url 'coffeapp:products-page' %}">
    <div class="image-1">
      {{product.avatar }}
    </div>
    <div class="product-1">
      {{product}}
    </div>
    
    <span class="container-1">
    هزار تومان{{product.price}}
    </span>
  </a>
  
  {% endfor %}
</div>

{% endblock content%}

coffeshop/coffeapp/templates/manage-product.html
{% extends "main.html" %}


{% block content %}
<p>Current Coffee: {{ storage.coffee }}</p>
<p>Current Sugar: {{ storage.sugar }}</p>
<p>Current Chocolate: {{ storage.chocolate }}</p>
<p>Current Flour: {{ storage.flour }}</p>
<div>
  <form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit", value='Update'>Update</button>
</form>
</div>


{% endblock content %}

coffeshop/coffeapp/templates/new_product.html
{% extends "main.html" %}



{% block content %} 
<div>
  <form action="" method='POST'>
    {% csrf_token %}
    {{form}}
    <input type="submit" value='Submit'>

  </form>


</div>


{% endblock content %}

coffeshop/coffeapp/templates/order_history.html
{% extends 'base.html' %}

{% block content %}
<h2>صفحه‌ی سوابق خرید</h2>

<p>سفارش های شما:</p>

{% if orders %}
    <table>
        <thead>
            <tr>
                <th>شماره سفارش</th>
                <th>محصولات</th>
                <th>مبلغ خرید</th>
                <th>نوع سفارش</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.order_id }}</td>
                <td>{{ order.products }}</td>
                <td>{{ order.purchase_amount }}</td>
                <td>{% if order.type %}حضوری{% else %}آنلاین{% endif %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>شما هنوز سفارشی ثبت نکرده‌اید.</p>
{% endif %}
{% endblock %}

coffeshop/coffeapp/templates/products.html
{% extends 'main.html' %}

{% block content %}

<div>
  {% for product in products %}
    <div class="image-1">
      {{product.avatar }}
    </div>
    <div class="product-1">
      {{product.name}}
    </div>
    
    <span class="container-1">
    هزار تومان{{product.price}}
    </span>

    <a class="buy-now-button" href="{% url 'coffeapp:add_to_cart' product_id=product.id %}">Add to Cart</a>
  
  {% endfor %}
</div>
<div>
  <h3>فیلتر ها</h3>
  <hr>
  <div>
    {% comment %} {% for product in products %}
    {% if product.vertical not in displayed_verticals %}
        <div>{{ product.vertical }}</div>
        {% set displayed_verticals = displayed_verticals|merge({product.vertical: true}) %}
    {% endif %}
{% endfor %} {% endcomment %}
    {%for product in products%}
    <li>
      <a href="{% url 'coffeapp:products-page' %}?q{{product.vertical}}">{{product.vertical}}</a>

      






    </li>
      {% endfor %}
    {% comment %} {% for price in product_prices %}
    <div>
      {{price}}



    </div>
    {% endfor %}
  </div> {% endcomment %}
</div>
{% endblock content%}

coffeshop/coffeapp/templates/store_management.html
{% extends 'base.html' %}

{% block content %}
<h1>صفحه مدیریت فروشگاه</h1>

<div class="row">
    <div class="col-md-8">
        <h2>نمودار فروش</h2>
        <div id="chart"></div>

        <h2>لیست فروش</h2>
        <ul>
        {% for sale in sales %}
            <li>{{ sale.product.name }} - قیمت: {{ sale.price }} - تعداد: {{ sale.amount }}</li>
        {% endfor %}
        
        
        <h2>لیست محصولات</h2>
        <ul>
        {% for product in products %}
            <li>{{ product.name }} - موجودی: {{ product.amount }}</li>
        {% endfor %}
        </ul>
    </div>
    
    <div class="col-md-4">
        <h2>مدیریت انبار</h2>
        <ul>
        {% for item in storage_data %}
            <li>{{ item.name }}: {{ item.amount }}</li>
        {% endfor %}
        </ul>
        
        <h2>اضافه کردن محصول</h2>
        <a href="{% url 'coffeapp:new-product' %}" class="btn btn-primary">افزودن محصول جدید</a>
    </div>
</div>
{% endblock %}